### ISSUE TITLE
error when pip install -r requirements.txt

### ISSUE THREAD

**Issue by JASON0916** [Storj/pyp2p#10]
# Problem:
Although i installed pip 7.1.2 in my virtualenv, Error is raised when i use 
`pip install -r requirements.txt`.
## System:
OSX10.10.5
## Python Version:
2.7.10(using virtualenv) & pip 7.1.2
## Error message:
`Exception:
Traceback (most recent call last):
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/basecommand.py", line 291, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/req/req_file.py", line 137, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
    reqs = list(parse_requirements(s))
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
    "version spec")
  File "/Users/jason/opensource/pyp2p/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected version spec in pip 7.1.2 at  7.1.2
`
# Solution:
I remove `pip 7.1.2` and then everything go on smoothly.

**Comment by robertsdotpm** [comment]
Any chance you can elaborate on what the problem was? Did there used to be a pip line in requirements.txt?

**Comment by JASON0916** [comment]
I used `pip install -r requirements.txt` and error was raised. And then i found there was a pip line in requirements.txt. Since there isn't a pip line in requirements.txt now, it no longer matters.

**Comment by robertsdotpm** [comment]
Ok, cool. I'll close the issue then
