### ISSUE TITLE
Fix tests and update pyp2p.dht_msg.DHT api.

### ISSUE THREAD

**Issue by F483** [Storj/pyp2p#15]
I changed the storjnode api so that direct messages are removed and the message handlers no longer get the source node id (always unknown with relay messages). `pyp2p.dht_msg.DHT` needs to be updated to reflect this change.

See https://github.com/Storj/storjnode/commit/a7bee2cfcea17a7c2f936b2c92215b5df372313d#diff-f02d8d10fcbce54955b651de4d023a1cR30

The current master branch however does not build (why is the develop branch so far behind?) any maybe its better if @robertsdotpm takes a look at it as he knows this code well.

```
======================================================================
ERROR: test_0000001_sock (tests.test_sock.test_sock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_sock.py", line 249, in test_0000001_sock
    blocking=1)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
ERROR: test_blocking_timeout (tests.test_sock.test_sock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_sock.py", line 193, in test_blocking_timeout
    s = Sock(rendezvous_servers[0]["addr"], rendezvous_servers[0]["port"], blocking=1)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
ERROR: test_encoding (tests.test_sock.test_sock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_sock.py", line 208, in test_encoding
    s = Sock(rendezvous_servers[0]["addr"], rendezvous_servers[0]["port"], blocking=1)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
ERROR: test_non_blocking_timeout (tests.test_sock.test_sock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_sock.py", line 202, in test_non_blocking_timeout
    s = Sock(rendezvous_servers[0]["addr"], rendezvous_servers[0]["port"], blocking=0)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
ERROR: test_recv_recvline_switch (tests.test_sock.test_sock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_sock.py", line 221, in test_recv_recvline_switch
    s = Sock(rendezvous_servers[0]["addr"], rendezvous_servers[0]["port"], blocking=1)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
ERROR: test_00001 (tests.test_rendezvous_server.test_rendezvous_client)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_rendezvous_server.py", line 13, in test_00001
    rendezvous_servers[0]["port"], blocking=1)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 77, in __init__
    self.connect(addr, port)
  File "/home/f483/dev/storj/pyp2p/pyp2p/sock.py", line 187, in connect
    raise socket.error("Socket connect failed.")
error: Socket connect failed.

======================================================================
FAIL: test_00000002 (tests.test_net.test_net)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_net.py", line 566, in test_00000002
    assert(0)
AssertionError

======================================================================
FAIL: test_nat_tcp_hole_punch (tests.test_net.test_net)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_net.py", line 56, in test_nat_tcp_hole_punch
    assert(0)
AssertionError

======================================================================
FAIL: test_net_config (tests.test_net.test_net)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/f483/dev/storj/pyp2p/tests/test_net.py", line 348, in test_net_config
    assert(conf_out == found)
AssertionError

----------------------------------------------------------------------
```

**Comment by robertsdotpm** [comment]
I was only using the master branch, wasn't aware this repo even had develop.

Also: based on this error it looks like maybe there was a network problem connecting to one of the rendezvous servers? There might have been congestion - they're on pretty terrible / low-end VPS.

Where did you get these errors out of curiosity? Was it on your home PC? Travis, or ... something else?

**Comment by robertsdotpm** [comment]
This should be fixed too
